
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS user_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS first_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS registration_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS onboarding_status TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS engagement_status TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_contact_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS follow_up_required BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS assigned_agent TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_clients_email_lower ON public.clients (lower(email)) WHERE email <> '';
